### ISSUE TITLE
Using the qauth.php

### ISSUE THREAD

**Issue by jarodthornton** [JonTheWong/whmcs_autoauth#4]
Can anyone confirm this works?

**Comment by JonTheWong** [comment]
confirmed working on 7.1.1

Regards,




Founder & Cloud Farmer
Zenith Media Canada

1-514-316-1366
1-647-848-1366
1-855-ZENITH-0

Extension: 1337

@JonTheWong <https://twitter.com/JonTheWong>

www.zenithmedia.ca <https://www.zenithmedia.ca/>

**Comment by McGuyverBR** [comment]
Hi, people!
I'm using the whmcsjet.com modified version ( I'm McGuyver from http://maxserver.com.br ;) ) and confirm this is working on WHMCS version 7.2.2.

You only need to add the lines below in configuration.php, like informed by @JonTheWong on Readme.md:

```
$smarty_security_policy = array(
   'mail' => array(
      'php_modifiers' => array(
         'md5',
      ),
   ),
);
```


Hey, @JonTheWong If possible cloud you correct the site address? 👍 ;-)
Thank you a lot for your contribuition!

**Comment by JonTheWong** [comment]
Fixed the type-o

**Comment by jarodthornton** [comment]
Just to clarify, can someone outline how this works with quotes? I'm looking for a basic description of how this functions. As it stands, the quoting system doesn't have any "client" data to associate with a new quote. It does have "new client" data so I see how this could work. I'm hoping it will allow us to send a quote to new client and allow them to accept and automate the process of getting to a purchase page.

**Comment by JonTheWong** [comment]
@emajen 

What it does is just create a link  made up of the users email+time+hash
This allows them to click the link and automatically login to their account on whmcs. ( assuming they have an account )

If you use it on quotes it will allow them to pay automatically if they have a credicard / paypal on file.
Since they are logged in automatically and hit pay.

All in all it saves a few steps for the user.

**Comment by jarodthornton** [comment]
@JonTheWong 

This assumes they have an account, which isn't generally the case in the event the quote is created for a "New Client." Correct?

**Comment by JonTheWong** [comment]
@emajen You need to create the account before you send a quote. You can't send a quote without the minimum of an email address in the account section.

In the proper sales funnel process.
When a client requests a quote, you create an account with the company information your quoting.

This allows you to continue the sales process without going backwards. plus this allows you to track who is asking for quotes, and allows you to call them back for a followup and even automate emails for reminders.

**Comment by jarodthornton** [comment]
Correct, but in WHMCS it does not actually create an account. If you just create a new quote and add new client info and save, it does not create a client in WHMCS.

**Comment by JonTheWong** [comment]
ah your talking about making a quote in "quotes.php?action=manage"

Where you send a quote and fill in the information.
We don't send quotes like that probably because of the auto login.

I'm not sure if it does create a client; We just always create a new client when they call and then send a quote via the "existing client tab"

In this specific case. I would need to do some testing. But if we look at the code it focuses on the quote ID and not the account id. So in theory it should still work.

email + timestamp + hash is the login and its directing it to viewquote.php?id=

Since no "account ID" is present then it shouldn't matter. Feel free to give us feedback.

**Comment by jarodthornton** [comment]
That is exactly the funnel we are working with. In your script you have yourdomain.com/eauth.php?email={$client_email}&invoice={$invoice_num}&hash={$hash|md5} - do you mind rebuilding that to reflect what it would look like with a quote instead of an invoice?

**Comment by JonTheWong** [comment]
the repo has two files. eauth and qauth, qauth is built for quotes.

https://github.com/JonTheWong/whmcs-autoauth-invoice/blob/master/qauth.php

**Comment by JonTheWong** [comment]
{$whmcs_url}/qauth.php?email={$client_email}&amp;quote={$quote_number}&amp;hash={$hash|md5}
